# Generated by Django 5.0.6 on 2024-07-03 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entidades', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Maestrías',
            new_name='Maestrias',
        ),
    ]
