# Generated by Django 5.0.6 on 2024-07-04 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entidades', '0002_rename_maestrías_maestrias'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sustentacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_sust', models.DateField()),
                ('lugar', models.CharField(max_length=30)),
                ('mencion', models.CharField(max_length=100)),
            ],
        ),
    ]
